name: CD Pipeline

on:
  push:
    branches: ['develop']
  workflow_run:
    workflows: ['CI Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull bilanox/bookio:latest
      - name: Delete Old docker container
        run: sudo docker rm -f bookio-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 3001:3001 --name bookio-container bilanox/bookio
